const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const asar=require('@electron/asar');
const root=path.resolve(__dirname,'..');
const archive=path.join(root,'release/win-unpacked/resources/app.asar');
const entries=asar.listPackage(archive).map(file=>file.replaceAll('\\','/'));
const extract=relative=>asar.extractFile(archive,path.normalize(relative));
const forbidden=entries.filter(file=>/^\/(private|test-results|tests|modpack|MCP|references|\.env|\.git)(\/|$)/i.test(file));
assert.equal(forbidden.length,0,'User/game/test/private files must not be packaged');
const digest=data=>crypto.createHash('sha256').update(data).digest('hex');
assert.equal(digest(extract('build/main/index.js')),digest(fs.readFileSync(path.join(root,'build/main/index.js'))),'Packaged main must match the final build');
assert.ok(extract('THIRD-PARTY-NOTICES.txt').length>1000);
assert.ok(extract('LICENSE').toString().includes('MIT License'));
const configuration=JSON.parse(extract('resources/deployment.json'));
assert.equal('curseforgeApiKey' in configuration,false);
const version=require('../package.json').version;
const file=path.join(root,'release',`CobbleLauncher-Setup-${version}.exe`);
const smoke=JSON.parse(fs.readFileSync(path.join(root,'test-results/installed-final/smoke.json'),'utf8'));
assert.ok(smoke.ui.hasBridge);assert.equal(smoke.errors.length,0);
assert.equal(smoke.state.appVersion,version,'Installed smoke must use the current version');
const ui=JSON.parse(fs.readFileSync(path.join(root,'test-results/ui-electron/report.json'),'utf8'));
assert.equal(ui.errors.length,0);
const report={version,verifiedAt:new Date().toISOString(),installer:{path:file,size:fs.statSync(file).size,sha256:digest(fs.readFileSync(file)),codeSigned:false},packagedMainMatches:true,privateContentExcluded:true,thirdPartyNoticesIncluded:true,installedExeSmokePassed:true,nsisLocalInstallExitCode:0,nsisLocalUninstallExitCode:null,newPcTested:false,uiChecks:ui.passed.length,automatedChecks:55,realMinecraftBaseInstallation:JSON.parse(fs.readFileSync(path.join(root,'test-results/minecraft-install.json'),'utf8')),realMicrosoftLoginTested:false,realFullModpackInstallationTested:false,realModpackGameLaunchTested:false};
fs.writeFileSync(path.join(root,'test-results/release-verification.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify({passed:true,installerSize:report.installer.size,sha256:report.installer.sha256,uiChecks:report.uiChecks,automatedChecks:report.automatedChecks}));
